apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service-postgresql
data:
  DB_HOST: postgresql-service
  DB_PORT: 5432
  DB_USERNAME: myuser
  DB_NAME: mydatabase
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
type: Opaque
data:
  password: bXlwYXNzd29yZA==